services:
  - type: web
    name: fresh-life-style
    env: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromGroup: shared-db-settings
      - key: GEMINI_API_KEY
        sync: false
      - key: NODE_VERSION
        value: 20.11.0
